example multi agents
aol/qiao pull request #6
Opened 2017-06-07 13:49 UTC by matarrese

2017-06-07 13:55 UTC, ytung05 commented on examples/MultiAgentsLog2Kafka/src/main/resources/qiao.xml
> +      <property name="fileBookKeeper" ref="fileBookKeeper" />
Valid property names for agent are 'bookKeeper' and 'fileManager'.

2017-06-07 13:57 UTC, ytung05 commented on examples/MultiAgentsLog2Kafka/src/main/resources/qiao.xml
> +            <property name="doneFileHandler" ref="doneFileHandler" />
Remove doneFileHandler and fileBookKeeper.  They are injected internally by the bootstrapping process.

2017-06-07 13:58 UTC, ytung05 commented on examples/MultiAgentsLog2Kafka/src/main/resources/qiao.xml
> +            <property name="fileBookKeeper" ref="fileBookKeeper" />
Remove fileBookKeeper.  BookKeeper is injected internally.

2017-06-07 14:00 UTC, ytung05 commented on examples/MultiAgentsLog2Kafka/src/main/resources/beans.xml
> +   <bean id="fileManager-2" class="com.aol.advertising.qiao.injector.file.watcher.QiaoFileManager">
See Examples/Log2Kafka for example.  No need to define doneFileHandler bean.

2017-06-08 16:43 UTC, matarrese commented
@ytung05 please review this new updates, thanks

2017-06-08 17:41 UTC, ytung05 requested changes
Please remove all the files related to qiao_cache.

2017-06-09 14:44 UTC, matarrese commented
Hi @ytung05 I saw there are some cached files as well in the folder Log2Kafka on this branch , should they be removed as well from there?

2017-06-09 14:53 UTC, merged

2017-06-09 15:20 UTC, ytung05 commented
The qiao_cache directory in Log2Kafka has been removed.  PR #6 has been merged.  Thanks.